spring.config.import=optional:file:.env[.properties]
server.port=${PORT:5000}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
mqtt.url=${MQTT_URL}
mqtt.user=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}
