services:
  - type: web
    name: smartbee-backend
    env: docker
    region: ohio
    plan: free
    dockerCommand: ""
    healthCheckPath: /api/test/config
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MQTT_URL
        sync: false
      - key: MQTT_USER
        sync: false
      - key: MQTT_PASSWORD
        sync: false
